In [1]:
import numpy as np

In [2]:
mylist =[1,2,3]

In [3]:
arr = np.array(mylist)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.39135724, 0.90736472, 0.87295959, 0.30105528, 0.36220077])

In [14]:
np.random.rand(5,5)

array([[0.63510682, 0.6335944 , 0.50483257, 0.07107297, 0.68501928],
       [0.08855319, 0.64872603, 0.14042611, 0.0911077 , 0.4572669 ],
       [0.00769977, 0.78636604, 0.48526707, 0.86587351, 0.83314881],
       [0.0230899 , 0.99322623, 0.9203152 , 0.07840907, 0.98535304],
       [0.42195105, 0.14385707, 0.24467485, 0.01372955, 0.41957086]])

In [15]:
np.random.randn(5,5)

array([[ 0.01442917, -1.18856596,  0.28816834, -0.12112094, -3.54770516],
       [ 0.10388711, -0.5801788 , -1.12903409,  0.35567656, -2.19814908],
       [ 1.78065952, -1.44212166,  0.430824  , -1.15820972, -0.6968965 ],
       [-1.04466057,  1.79388755,  0.31939926, -1.32712179,  1.01171855],
       [ 0.57803218,  1.45733185,  0.07735079,  0.1295684 ,  0.88268515]])

In [16]:
np.random.randint(1,50,10)

array([ 5, 27, 27, 35, 25,  5,  9,  4,  2,  4])

In [17]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [18]:
arr
#ranarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
ranarr.max()

46

In [22]:
ranarr.min()

0

In [23]:
ranarr.argmax()

9

In [24]:
ranarr.argmin()

6

In [25]:
arr = arr.reshape(5,5)

In [26]:
arr.shape

(5, 5)

In [27]:
arr.dtype

dtype('int32')

In [28]:
arr = np.arange(0,11)

In [29]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [30]:
sliceofarr = arr[0:6]

In [31]:
sliceofarr[:] = 99


In [32]:
sliceofarr

array([99, 99, 99, 99, 99, 99])

In [33]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
arr_2d[0][2]

15

In [37]:
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [38]:
arr[:] = 0

In [39]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
import pandas as pd

In [41]:
from numpy.random import randn

In [42]:
np.random.seed(101)

In [43]:
df = pd.DataFrame(randn(5,4),["a",'b','c','d','e'],['w','x','y','z'])

In [44]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [45]:
df['w']

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [46]:
type(df)

pandas.core.frame.DataFrame

In [47]:
type(df['w'])

pandas.core.series.Series

In [48]:
df.x

a    0.628133
b   -0.319318
c    0.740122
d   -0.758872
e    1.978757
Name: x, dtype: float64

In [49]:
df['new'] = df['w'] + df['y']

In [50]:
df

w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [51]:
df.drop('new',axis=1)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [52]:
df.drop('e',axis=0)

w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542

In [53]:
df

w         x         y         z       new
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [54]:
df.drop('new',axis=1,inplace=True)

In [55]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [56]:
df.loc['a']

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: a, dtype: float64

In [57]:
df.loc[ ['a','b'],['w','y'] ]

w         y
a  2.706850  0.907969
b  0.651118 -0.848077

In [58]:
df.iloc[2]

w   -2.018168
x    0.740122
y    0.528813
z   -0.589001
Name: c, dtype: float64

In [59]:
booldf = df > 0

In [60]:
df[booldf]

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118       NaN       NaN  0.605965
c       NaN  0.740122  0.528813       NaN
d  0.188695       NaN       NaN  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [61]:
df['w']>0

a     True
b     True
c    False
d     True
e     True
Name: w, dtype: bool

In [62]:
df[df['w']>0]['y']

a    0.907969
b   -0.848077
d   -0.933237
e    2.605967
Name: y, dtype: float64

In [63]:
df[(df['w']>0) & (df['y'] > 1)]

w         x         y         z
e  0.190794  1.978757  2.605967  0.683509

In [64]:
df.reset_index()

index         w         x         y         z
0     a  2.706850  0.628133  0.907969  0.503826
1     b  0.651118 -0.319318 -0.848077  0.605965
2     c -2.018168  0.740122  0.528813 -0.589001
3     d  0.188695 -0.758872 -0.933237  0.955057
4     e  0.190794  1.978757  2.605967  0.683509

In [65]:
newind = 'CA NY WY OR CO'.split()

In [66]:
df['States'] = newind

In [67]:
df

w         x         y         z States
a  2.706850  0.628133  0.907969  0.503826     CA
b  0.651118 -0.319318 -0.848077  0.605965     NY
c -2.018168  0.740122  0.528813 -0.589001     WY
d  0.188695 -0.758872 -0.933237  0.955057     OR
e  0.190794  1.978757  2.605967  0.683509     CO

In [68]:
df.set_index('States')

w         x         y         z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [69]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [70]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [71]:
inside

[1, 2, 3, 1, 2, 3]

In [72]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [73]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [74]:
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [75]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

In [76]:
df.index.names = ["Groups",'Num']

In [77]:
df

A         B
Groups Num                    
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [78]:
df.loc['G2'].loc[2]['B']

0.07295967531703869

In [79]:
df.loc['G1'].loc[3]['A']

-0.13484072060601238

In [80]:
df.loc['G1']

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [81]:
df.xs('G1')

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [82]:
df.xs(1,level='Num')

A         B
Groups                    
G1      0.302665  1.693723
G2      0.166905  0.184502

In [83]:
f = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [84]:
f

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [85]:
f.dropna()

A    B  C
0  1.0  5.0  1

In [86]:
f.dropna(axis = 1)

C
0  1
1  2
2  3

In [87]:
f.dropna(thresh=1)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [88]:
f

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [89]:
f.fillna(value = 'Fill')

A     B  C
0   1.0   5.0  1
1   2.0  Fill  2
2  Fill  Fill  3

In [90]:
f['A'].fillna(value=df['A'].mean())

0    1.000000
1    2.000000
2    0.012523
Name: A, dtype: float64

In [91]:
f

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [92]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [93]:
df = pd.DataFrame(data)

In [94]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [95]:
by_comp = df.groupby("Company")

In [96]:
#by_comp.std()

In [97]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [98]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [99]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [100]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [101]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [102]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [103]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [104]:
pd.concat([df1,df2,df3],axis=1).fillna(value='Fill')

A     B     C     D     A     B     C     D     A     B     C     D
0     A0    B0    C0    D0  Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill
1     A1    B1    C1    D1  Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill
2     A2    B2    C2    D2  Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill
3     A3    B3    C3    D3  Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill
4   Fill  Fill  Fill  Fill    A4    B4    C4    D4  Fill  Fill  Fill  Fill
5   Fill  Fill  Fill  Fill    A5    B5    C5    D5  Fill  Fill  Fill  Fill
6   Fill  Fill  Fill  Fill    A6    B6    C6    D6  Fill  Fill  Fill  Fill
7   Fill  Fill  Fill  Fill    A7    B7    C7    D7  Fill  Fill  Fill  Fill
8   Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill    A8    B8    C8    D8
9   Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill    A9    B9    C9    D9
10  Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill   A10   B10   C10   D10
11  Fill  Fill  Fill  Fill  Fill  Fill  Fill  Fill   A11   B11   C11   D11

In [105]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})   

In [106]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [107]:
right


key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [108]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [109]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [110]:
pd.merge(left, right, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [111]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [112]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [113]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [114]:
left.join(right,how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [115]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [116]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [117]:
df = pd.read_csv('example')

In [118]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [119]:
df.to_csv('My_output',index=False)

In [120]:
pd.read_csv('My_output')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [122]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [123]:
df.to_excel('Excel_Sample2.xlsx',sheet_name='NewSheet')

In [126]:
data = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [128]:
data[0].head()

Bank NameBank           CityCity StateSt  CertCert   
0         First Republic Bank      San Francisco      CA     59017  \
1              Signature Bank           New York      NY     57053   
2         Silicon Valley Bank        Santa Clara      CA     24735   
3           Almena State Bank             Almena      KS     15426   
4  First City Bank of Florida  Fort Walton Beach      FL     16748   

               Acquiring InstitutionAI Closing DateClosing  FundFund  
0            JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
1                  Flagstar Bank, N.A.      March 12, 2023     10540  
2  First–Citizens Bank & Trust Company      March 10, 2023     10539  
3                          Equity Bank    October 23, 2020     10538  
4            United Fidelity Bank, fsb    October 16, 2020     10537

In [129]:
from sqlalchemy import create_engine

In [130]:
engine = create_engine('sqlite:///:memory:')

In [131]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [132]:
df.to_sql('my_table',engine)

4

In [133]:
sqldf = pd.read_sql('my_table', con=engine)

In [134]:
sqldf

index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

In [135]:
sal = pd.read_csv('Salaries.csv')

In [136]:
sal.head()

Id       EmployeeName                                        JobTitle   
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  \
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits   
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43  \
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [137]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [138]:
sal['BasePay'].mean()

66325.4488404877

In [139]:
sal['OvertimePay'].max()

245131.88

In [140]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [141]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [143]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]

Id    EmployeeName                                        JobTitle   
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  \

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits   
0  167411.18          0.0  400184.25       NaN  567595.43         567595.43  \

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN

In [144]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]

Id EmployeeName                    JobTitle  BasePay  OvertimePay   
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0  \

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes   
148653   -618.13       0.0   -618.13           -618.13  2014    NaN  \

               Agency  Status  
148653  San Francisco     NaN

In [149]:
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [150]:
sal['JobTitle'].nunique()

2159

In [151]:
sal['JobTitle'].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [152]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

202

In [153]:
def chief_string(title):
  if 'chief' in title.lower().split():
    return True
  elif 'chief,' in title.lower().split():
    return True
  else:  
    return False

In [155]:
sum(sal['JobTitle'].apply(lambda x:chief_string(x)))

627

In [156]:
sal['title_len'] = sal['JobTitle'].apply(len)

In [157]:
sal[['title_len','TotalPayBenefits']].corr()

title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000